### ISSUE TITLE
Add clearer instructions and details to README.md

### ISSUE THREAD

**Issue by AnnieDebbie** [Engineervinay/search-hackernews#5]

**Comment by Engineervinay** [comment]
pull request is merged, now it will count towards hacktoberfest.

**Comment by AnnieDebbie** [comment]
Thank you @Engineervinay 
I'm still waiting to hear your feedback about the screenshots section. To recap, I had asked which you would prefer:
- Leave the screenshots as they are
- Use screenshots of the app's UI as it is
- Delete the section entirely till the UI is redone

**Comment by Engineervinay** [comment]
for Now, we can leave the screenshots as they are. I will work on the theme again to remove bootstrap and add material UI for the Project theme.

**Comment by AnnieDebbie** [comment]
Hello
I hope you are doing well
Thanks for your response.
I have started working on the UI..
I converted the comments from html to plain text. I can push that and create a PR if you'd like

Also, I reached out to a product designer friend of mine to design the screens which I will then code. I hope you don't mind. 

If you approve, send me your email address so you can be given access to the Figma file. Or, I can send screenshots of the screens
